[package]
name = "g1t"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde_json = "1.0.148"
sha-1 = "0.10.1"
vfs = "0.12.2"
virtual-filesystem = "0.2.1"
